# Generated by Django 3.2 on 2021-05-01 15:11

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

TOWNS_FILENAME = 'export.json'

def load_data(apps, schema_editor):
    Town = apps.get_model('nearbytowns', 'Town')
    jsonfile = Path(__file__).parents[2] / TOWNS_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Town(name=name, location = location).save()
            except KeyError:
                pass     

class Migration(migrations.Migration):

    dependencies = [
        ('nearbytowns', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
